### ISSUE TITLE
[Feature Request] Dump RSX (GDDR) Memory

### ISSUE THREAD

**Issue by LuanTeles** [Evilnat/Cobra-PS3#26]
Can this option be added?

So we'll get
-LV1
-LV2
-RSX (the requested)
-RAM

and an option to ALL memory?

**Comment by LuanTeles** [comment]
Can this option be added?

**Comment by Evilnat** [comment]
I can add it but I don't know if dumped data is fine and correct, do you have any RSX dump?

**Comment by LuanTeles** [comment]
You can dump it via webman /dump.ps3?rsx 

But unfortunatelly my system is getting KP when i run the command o.O

**Comment by Evilnat** [comment]
I can add it mate, I will do it ;)
