### ISSUE TITLE
Some issues with Evilnat 4.89.3 [PEX] [DEX]

### ISSUE THREAD

**Issue by Windows10User2** [Evilnat/Cobra-PS3#36]
So, to summarize, I'm having these problems in Evilnat 4.89.3 Cobra 8.4 [PEX] [CEX]:

1 - As soon as I click "Enable FTP" in "Cobra Tools" with an USB device attached to the PS3, the latter freezes (I tested this in another PS3 Slim and a friend of mine also did it in his PS3 Slim and we're having this problem too);

2 - The PS3 often freezes/beeps thrice and restarts when returning to XMB after having transferred files with FileZilla or WinSCP to the PS3;

3 - If I delete a FileZilla or WinSCP FTP transfer to the PS3 while IRISMAN is running and the transfer is being made, the following FTP transfers start very slowly (like under 1 MiB/s instead of 21 something MiB/s) and take time to reach the right speed (21 something MiB/s);

4 - If I leave FileZilla or WinSCP connected to the PS3 for some time, I can't reconnect to it until I close FileZilla or WinSCP and run them again.

I reinstalled FileZilla, Evilnat 4.89.3 Cobra 8.4 [PEX] [CEX] and IRISMAN, used the Restore File System and Rebuild Database settings from the Recovery Menu and swapped the HDD for the previous one and for a new SSD (the FTP transfer speed went from 18 something MiB/s to 21 something MiB/s) and I still have these issues.

EDIT: If I close FileZilla or WinSCP after transferring files, I can go back to XMB from IRISMAN without the PS3 freezing.

EDIT 2: If I return to XMB from multiMAN and Rebug Toolbox after transferring files to the PS3 with FileZIlla or WinSCP without closing them, the PS3 doesn't freeze/beep thrice and restart, so maybe it's IRISMAN's fault (as well as the second issue). Also, the third issue happens if using multiMAN, Rebug Toolbox and Cobra's FTP too.

**Comment by CHA0SHACKER** [comment]
This repository is just about Cobra and not really the CFW that EvilNat also develops. For support about that you’re better off writing him on Twitter or creating a thread on psx-place.com

**Comment by Windows10User2** [comment]
> This repository is just about Cobra and not really the CFW that EvilNat also develops. For support about that you’re better off writing him on Twitter or creating a thread on psx-place.com

I don't have a twitter account nor do I want to create one and I was banned from PSX Place. Anyway, I did the latter[](https://www.psx-place.com/threads/ps3-freezes-as-soon-as-i-click-enable-ftp-in-evilnat-4-89-3-with-an-external-hdd-attached.39462/), Evilnat answered me and he/she couldn't help me.
